name: Symfony

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  symfony-tests:
    runs-on: ubuntu-latest
    steps:
    #  To automatically get bug fixes and new Php versions for shivammathur/setup-php,
    # change this to (see https://github.com/shivammathur/setup-php#bookmark-versioning):
    # uses: shivammathur/setup-php@v2
    - uses: shivammathur/setup-php@2cb9b829437ee246e9b3cac53555a39208ca6d28
      with:
        php-version: '8.1'
    - uses: actions/checkout@v3
    - name: Copy .env.test.local
      run: php -r "file_exists('.env.test.local') || copy('.env.test', '.env.test.local');"
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
    - name: Install Railway
      run: npm i -g @railway/cli
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Run Migration && Load Fixtures
      run: |
        composer dump-autoload
        composer require --dev symfony/orm-pack
        php bin/console doctrine:database:drop --if-exists --force --env=prod
        php bin/console doctrine:database:create --if-not-exists --env=prod
        php bin/console doctrine:migrations:migrate --env=prod || echo "No migrations found or migration failed"
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
    - name: Deploy
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      run: railway up
    - name: npm install
      uses: actions/setup-node@v2
      with:
        node-version: '18'
    - run: npm install --force
    - run: npm run watch
